name: admin_banja
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 2.0.7+7

environment:
  sdk: ">=3.0.3 <4.0.0"


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  awesome_circular_chart: ^1.0.0
  bouncing_widget: ^2.0.0
  cupertino_icons: ^1.0.2
  flutter_svg:
  fl_chart: ^0.40.2
  flutter_local_notifications: ^15.1.0+1
  firebase_messaging: ^14.6.6
  flutter_phoenix: ^1.1.1
  flutter_screenutil: ^5.8.4
  flutter_slider_drawer: ^2.1.3
  get: ^4.6.5
  get_storage:
  image_picker: ^1.0.2
  intl: ^0.18.1
  lottie: ^2.6.0
  oktoast: ^3.3.1
  path_provider: ^2.1.0
  share_plus: ^7.1.0
  modal_bottom_sheet: ^2.1.2
  card_swiper: ^3.0.1
  syncfusion_flutter_gauges: ^22.2.9
  nanoid: ^1.0.0
  flutter_nfc_kit: ^3.3.1
  firebase_core: ^2.15.1
  nfc_manager: ^3.3.0
  share_plus_web: ^3.1.0
  http: ^1.1.0
  multipart_request_null_safety: ^0.3.4

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.2

flutter_icons:
  ios: true
  android: true
  image_path: "assets/images/ic_launcher.png"
  adaptive_icon_foreground: "assets/images/ic_foreground.png"
  adaptive_icon_background: "assets/images/ic_background.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/lotties/

  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins/Poppins-Light.ttf

